## Python Pandas

## Import Pandas

In [1]:
import pandas as pd

## Mengenal DataFrame

#### Membuat DataFrame sederhana

In [2]:
pd.DataFrame(data={'Minuman': ['Susu', 'Kopi'], 
                   'Harga': [4500, 3200]})

  Minuman  Harga
0    Susu   4500
1    Kopi   3200

#### Mengenal index pada DataFrame

In [3]:
pd.DataFrame(data={'Budi': ['suka', 'suka'], 
                   'Wati': ['tidak suka', 'suka.']},
             index=['Mangga', 'Jambu'])

        Budi        Wati
Mangga  suka  tidak suka
Jambu   suka       suka.

## Mengenal Series

In [4]:
pd.Series(data=[100, 150, 200, 250, 300])

0    100
1    150
2    200
3    250
4    300
dtype: int64

In [5]:
pd.Series(data=[3000, 3500, 40000], index=['Mangga', 'Pisang', 'Jambu'], name='Harga Buah')

Mangga     3000
Pisang     3500
Jambu     40000
Name: Harga Buah, dtype: int64

## Memuat File CSV ke dalam DataFrame

In [6]:
wine_df = pd.read_csv('./dataset/wine_data2.csv')
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [7]:
wine_df.head(10)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
8,8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
9,9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam

#### Melihat dimensi DataFrame dengan attribute ```shape```

In [8]:
wine_df.shape

(9391, 14)

#### Menggunakan salah satu kolom sebagai index

In [9]:
wine_df = pd.read_csv('./dataset/wine_data2.csv', index_col=0)
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [10]:
wine_df.shape

(9391, 13)

## Menyimpan DataFrame ke dalam File CSV

In [11]:
minuman_df = pd.DataFrame(data={'Minuman': ['Bandrek', 'Kopi Hitam'], 
                                'Harga': [4500, 3200]})
minuman_df

      Minuman  Harga
0     Bandrek   4500
1  Kopi Hitam   3200

In [12]:
minuman_df.to_csv('./output/minuman.csv')

#### Menyimpan DataFrame ke dalam file CSV tanpa menyertakan index

In [13]:
minuman_df.to_csv('./output/minuman.csv', index=False)

## Melakukan akses pada kolom DataFrame

In [14]:
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Terdapat dua cara untuk melakukan akses kolom pada DataFrame

### Cara 1: Sebagai atribute

In [15]:
wine_df.country

0           Italy
1        Portugal
2              US
3              US
4              US
          ...
9386           US
9387           US
9388           US
9389           US
9390    Argentina
Name: country, Length: 9391, dtype: object

### Cara 2: Sebagai dictionary index

In [16]:
wine_df['country']

0           Italy
1        Portugal
2              US
3              US
4              US
          ...
9386           US
9387           US
9388           US
9389           US
9390    Argentina
Name: country, Length: 9391, dtype: object

In [17]:
wine_df['country'][0]

'Italy'

## Melakukan akses data pada DataFrame

Terdapat dua mekanisme untuk melakukan akses data pada DataFrame: index-based selection dan label-based selection. <br/>
Kedua mekanisme akses ini mendahulukan baris (row) baru diikuti kolom (column).

### index-based selection
Mekanisme ini dapat dilakukan dengan memanfaatkan method ```iloc```

In [18]:
wine_df.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [19]:
wine_df.iloc[2, 0]

'US'

#### Slicing pada iloc

In [20]:
wine_df.iloc[:, 0]

0           Italy
1        Portugal
2              US
3              US
4              US
          ...
9386           US
9387           US
9388           US
9389           US
9390    Argentina
Name: country, Length: 9391, dtype: object

In [21]:
wine_df.iloc[0, :7]

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
designation                                         Vulkà Bianco
points                                                        87
price                                                        NaN
province                                       Sicily & Sardinia
region_1                                                    Etna
Name: 0, dtype: object

In [22]:
wine_df.iloc[1:3, 0]

1    Portugal
2          US
Name: country, dtype: object

#### Melewatkan list untuk melakukan akses data pada baris dan kolom tertentu dari DataFrame

In [23]:
wine_df.iloc[[0, 3, 8], 0]

0      Italy
3         US
8    Germany
Name: country, dtype: object

#### Menggunakan negative index untuk melakukan akses data pada baris dan kolom tertentu dari DataFrame

In [24]:
wine_df.iloc[-5:]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
9386,US,"Grown on the producer's 1,800-foot-high, dry-f...",NaN,93,48.0,California,Spring Mountain District,Napa,Virginie Boone,@vboone,Smith-Madrone 2012 Cabernet Sauvignon (Spring ...,Cabernet Sauvignon,Smith-Madrone
9387,US,Given slightly less new oak (60%) than the pro...,NaN,93,65.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Les Belles Collines 2012 Cabernet Sauvignon (N...,Cabernet Sauvignon,Les Belles Collines
9388,US,This is a Westside Road site known for its roc...,Flax Vineyard,93,57.0,California,Russian River Valley,Sonoma,Virginie Boone,@vboone,Merry Edwards 2013 Flax Vineyard Pinot Noir (R...,Pinot Noir,Merry Edwards
9389,US,"Very dark and inky in color, this bottling by ...",My Soul Is Rested,93,NaN,California,Central Coast,Central Coast,Matt Kettmann,@mattkettmann,Sanguis 2013 My Soul Is Rested Red (Central Co...,Red Blend,Sanguis
9390,Argentina,This ultraripe Malbec-led blend suggests aged ...,Alto,93,85.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Alta Vista 2011 Alto Red (Mendoza),Red Blend,Alta Vista

### label-based selection
Mekanisme ini dapat dilakukan dengan memanfaatkan method ```loc```

In [25]:
wine_df.loc[0, 'country']

'Italy'

In [26]:
wine_df.loc[0:5, 'country']

0       Italy
1    Portugal
2          US
3          US
4          US
5       Spain
Name: country, dtype: object

In [27]:
wine_df.loc[:, ['taster_name', 'taster_twitter_handle', 'points']].head()

          taster_name taster_twitter_handle  points
0       Kerin O’Keefe          @kerinokeefe      87
1          Roger Voss            @vossroger      87
2        Paul Gregutt           @paulgwine       87
3  Alexander Peartree                   NaN      87
4        Paul Gregutt           @paulgwine       87

### Alternatif lain
Alternatif lain untuk melakukan akses data dapat dilakukan dengan model akses kolom-baris (column-row)

In [28]:
wine_df[['country', 'province']][:].head()

    country           province
0     Italy  Sicily & Sardinia
1  Portugal              Douro
2        US             Oregon
3        US           Michigan
4        US             Oregon

In [29]:
wine_df[['country', 'province']][:5]

    country           province
0     Italy  Sicily & Sardinia
1  Portugal              Douro
2        US             Oregon
3        US           Michigan
4        US             Oregon

## Mengganti index

In [30]:
wine_df.set_index('title').head()
# df = wine_df.set_index('title')
# wine_df.set_index('title', inplace=True)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks

In [31]:
wine_df.reset_index().head()

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

## Seleksi data pada DataFrame
#### (Conditional Selection)

In [32]:
wine_df['country'] == 'Italy'

0        True
1       False
2       False
3       False
4       False
        ...
9386    False
9387    False
9388    False
9389    False
9390    False
Name: country, Length: 9391, dtype: bool

In [33]:
wine_df.loc[wine_df['country'] == 'Italy'].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì

In [34]:
wine_df.loc[(wine_df['country'] == 'Italy') & (wine_df['points'] >= 90)].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla

In [35]:
wine_df[(wine_df['country'] == 'Italy') & (wine_df['points'] >= 90)].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla

## Mengenal beberapa built-in method 
#### Mengenal method ```isin```

In [36]:
wine_df.loc[wine_df['country'].isin(['Italy', 'France'])].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer

#### Mengenal method ```isna``` dan ```notna```

In [37]:
wine_df[wine_df['price'].isna()].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN,Roger Voss,@vossroger,Domaine de la Madone 2012 Nouveau (Beaujolais...,Gamay,Domaine de la Madone
31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2010 Calanìca Nero d'Avola-...,Red Blend,Duca di Salaparuta
32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2011 Calanìca Grillo-Viogni...,White Blend,Duca di Salaparuta

In [38]:
wine_df[wine_df['price'].notna()].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem

## Menambah kolom baru pada DataFrame

Mendata seluruh kolom yang tersedia dengan attribute ```columns```

In [39]:
wine_df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

Menambah kolom baru dengan nama ```critic``` dan diberi nilai ```everyone``` untuk tiap baris.

In [40]:
wine_df['critic'] = 'everyone'
wine_df['critic'].head(10)

0    everyone
1    everyone
2    everyone
3    everyone
4    everyone
5    everyone
6    everyone
7    everyone
8    everyone
9    everyone
Name: critic, dtype: object

In [41]:
wine_df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery', 'critic'],
      dtype='object')

Menambah kolom baru dengan nama ```index_backwards``` dan diberi nilai bilangan bulat dari besar ke kecil sesuai dengan banyaknya jumlah baris.

In [42]:
wine_df['index_backwards'] = range(len(wine_df), 0, -1)
wine_df['index_backwards'].head()

0    9391
1    9390
2    9389
3    9388
4    9387
Name: index_backwards, dtype: int32

## Menghasilkan ringkasan (summary) data pada DataFrame

#### Mengenal method ```describe```, ```mean```,  ```unique```, ```value_counts```

In [43]:
wine_df.describe()

            points        price  index_backwards
count  9391.000000  8747.000000      9391.000000
mean     88.338409    35.361152      4696.000000
std       2.985455    45.102693      2711.092523
min      80.000000     4.000000         1.000000
25%      86.000000    17.000000      2348.500000
50%      88.000000    25.000000      4696.000000
75%      90.000000    42.000000      7043.500000
max     100.000000  1900.000000      9391.000000

In [44]:
wine_df['points'].describe()

count    9391.000000
mean       88.338409
std         2.985455
min        80.000000
25%        86.000000
50%        88.000000
75%        90.000000
max       100.000000
Name: points, dtype: float64

In [45]:
wine_df['points'].mean()

88.33840911511021

In [46]:
wine_df['taster_name'].describe()

count           7487
unique            18
top       Roger Voss
freq            1833
Name: taster_name, dtype: object

In [47]:
wine_df['taster_name'].unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams'], dtype=object)

In [48]:
wine_df['taster_name'].value_counts().head()

Roger Voss           1833
Michael Schachner    1140
Kerin O’Keefe         812
Virginie Boone        727
Paul Gregutt          669
Name: taster_name, dtype: int64

## Mengenal Mapping
Terdapat dua mekanisme mapping pada DataFrame, yaitu: dengan memanfaatkan method ```map``` dan method ```apply```

### Mengenal method ```map```
Diterapkan di tingkat Series

In [49]:
points_mean = wine_df['points'].mean()
wine_df['points'].map(lambda p: p - points_mean)

0      -1.338409
1      -1.338409
2      -1.338409
3      -1.338409
4      -1.338409
          ...
9386    4.661591
9387    4.661591
9388    4.661591
9389    4.661591
9390    4.661591
Name: points, Length: 9391, dtype: float64

### Mengenal method ```apply```
Diterapkan di tingkat DataFrame

In [50]:
points_mean = wine_df['points'].mean()

def remean_points(row):
    row['points'] = row['points'] - points_mean
    return row

wine_df.apply(remean_points, axis='columns').head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.338409,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,9391
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.338409,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,9390
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.338409,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,9389
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.338409,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,9388
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.338409,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,9387

### Alternatif lain dengan built-in operations
Mekanisme ini lebih cepat dan efisien (bila dibandingkan ```map``` dan ```apply```) tetapi tidak bisa menangani pemrosesan yang kompleks.

In [51]:
points_mean = wine_df['points'].mean()
wine_df['points'] - points_mean

0      -1.338409
1      -1.338409
2      -1.338409
3      -1.338409
4      -1.338409
          ...
9386    4.661591
9387    4.661591
9388    4.661591
9389    4.661591
9390    4.661591
Name: points, Length: 9391, dtype: float64

In [52]:
wine_df['country'] + ' - ' + wine_df['region_1']

0                        Italy - Etna
1                                 NaN
2              US - Willamette Valley
3            US - Lake Michigan Shore
4              US - Willamette Valley
                    ...
9386    US - Spring Mountain District
9387                 US - Napa Valley
9388        US - Russian River Valley
9389               US - Central Coast
9390              Argentina - Mendoza
Length: 9391, dtype: object

#### Kasus: Mencari title wine dengan proporsi points/price tertinggi dengan memanfaatkan method ```idmax```

In [53]:
wine_df.loc[(wine_df['points']/wine_df['price']).idxmax(), 'title']

'Felix Solis 2013 Flirty Bird Syrah (Vino de la Tierra de Castilla)'

In [54]:
wine_df['title'][(wine_df['points']/wine_df['price']).idxmax()]

'Felix Solis 2013 Flirty Bird Syrah (Vino de la Tierra de Castilla)'

Kasus: Mencari jumlah wine dengan description tropical dan fruity. Siapkan series untuk menampung jumlah dari kedua data.

In [55]:
n_tropical = wine_df['description'].map(lambda desc: 'tropical' in desc).sum()
n_fruity = wine_df['description'].map(lambda desc: 'fruity' in desc).sum()
pd.Series([n_tropical, n_fruity], index=['tropical', 'fruity'])

tropical    272
fruity      654
dtype: int64

#### Kasus: Melakukan konversi point menjadi star

In [56]:
def star_converter(row):
    if row['country'] == 'Canada':
        row['star'] = 3
    elif row['points'] >= 95:
        row['star'] = 3
    elif row['points'] >= 85:
        row['star'] = 2
    else:
        row['star'] = 1
    return row

wine_df['star'] = None
wine_df.apply(star_converter, axis='columns').head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards,star
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,9391,2
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,9390,2
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,9389,2
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,9388,2
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,9387,2

## Analisis terhadap sekelompok data

#### Kasus: menghitung jumlah data (rows/baris) untuk tiap points. <br/>
Cara pertama: dengan memanfaatkan method ```value_counts```

In [57]:
wine_df['points'].value_counts().head()

87    1349
88    1305
90    1040
86     935
89     866
Name: points, dtype: int64

Cara kedua: mengelompokkan data pada DataFrame terlebih dahulu dengan memanfaatkan method ```groupby```

In [58]:
wine_df.groupby('points')['points'].count().head()

points
80     16
81     42
82    117
83    256
84    450
Name: points, dtype: int64

#### Kasus: mendata wine reviewer beserta jumlah review yang pernah dilakukan.
Reviewer dapat diidentifikasi melalui kolom ```taster_name```

In [59]:
wine_df.groupby('taster_name')['taster_name'].count().head()

taster_name
Alexander Peartree     40
Anna Lee C. Iijima    280
Anne Krebiehl MW      204
Carrie Dykes            6
Fiona Adams             3
Name: taster_name, dtype: int64

#### Kasus: mencari harga terrendah dari setiap kelompok point

In [60]:
wine_df.groupby('points')['price'].min().head()

points
80    8.0
81    7.0
82    6.0
83    5.0
84    5.0
Name: price, dtype: float64

#### Kasus: menampilkan title dari wine untuk tiap country dengan points tertinggi
Data wine akan dikelompokkan terlebih dahulu berdasarkan negara, selanjutnya akan dicari wine di tiap kelompok negara yang memiliki points tertinggi

In [61]:
wine_df.groupby('country').apply(lambda df: df[ df['points'] == df['points'].max() ])[['title']].head()

                                                            title
country
Argentina 8869  Pascual Toso 2014 Finca Pedregal Single Vineya...
Armenia   8170     Van Ardi 2015 Estate Bottled Kangoun (Armenia)
Australia 345   Chambers Rosewood Vineyards NV Rare Muscat (Ru...
Austria   6736  Emmerich Knoll 2008 Ried Loibenberg Smaragd Gr...
          7864  Rosenhof 2012 Orion Eiswein Grüner Veltliner (...

#### Kasus: menampilkan title dari wine untuk tiap proviince di tiap country dengan points tertinggi

In [62]:
wine_df.groupby(['country','province']).apply(lambda df: df[ df['points'] == df['points'].max() ])[['title']].head()

                                                                             title
country   province
Argentina Mendoza Province 8869  Pascual Toso 2014 Finca Pedregal Single Vineya...
          Other            4633  El Esteco 2013 Chañar Punco Red (Calchaquí Val...
Armenia   Armenia          8170     Van Ardi 2015 Estate Bottled Kangoun (Armenia)
Australia Australia Other  893   Hungerford Hill 2008 Heavy Metal Shiraz (South...
          New South Wales  5290            Hope Estate 2009 Shiraz (Hunter Valley)

### Mengenal method ```agg```

In [63]:
wine_df.groupby('country')['price'].agg([len, min, max]).head()

             len   min    max
country
Argentina  289.0   6.0  215.0
Armenia      1.0  14.0   14.0
Australia  183.0   7.0  350.0
Austria    225.0  10.0   90.0
Brazil       2.0  31.0   36.0

#### Kasus: menampilkan harga (```price```) terrendah dan tertinggi untuk setiap jenis wine (```variety```)

In [64]:
wine_df.groupby('variety')['price'].agg(['min', 'max']).head()

              min   max
variety
Agiorgitiko  15.0  25.0
Aglianico    17.0  66.0
Albana       14.0  25.0
Albanello    20.0  20.0
Albariño     12.0  60.0

## Mengenal pengurutan data (sorting)

Membuat DataFrame yang lebih sederhana dengan tiga kolom

In [65]:
wine_simple_df = wine_df[['country', 'title', 'price']]
wine_simple_df.head()

    country                                              title  price
0     Italy                  Nicosia 2013 Vulkà Bianco  (Etna)    NaN
1  Portugal      Quinta dos Avidagos 2011 Avidagos Red (Douro)   15.0
2        US      Rainstorm 2013 Pinot Gris (Willamette Valley)   14.0
3        US  St. Julian 2013 Reserve Late Harvest Riesling ...   13.0
4        US  Sweet Cheeks 2012 Vintner's Reserve Wild Child...   65.0

#### Mengurutkan data berdasarkan price

In [66]:
wine_simple_df.sort_values(by='price').head()

       country                                              title  price
1987     Spain  Felix Solis 2013 Flirty Bird Syrah (Vino de la...    4.0
3950  Portugal  Adega Cooperativa Ponte de Barca 2010 Escolha ...    5.0
7605     Chile  San Pedro 2002 Gato Negro Cabernet Sauvignon (...    5.0
3167     Italy                   Anna Spinato NV Mini  (Prosecco)    5.0
8428        US  Earth's Harvest 2014 Organic Grapes Chardonnay...    5.0

#### Pengurutan secara descending (dari nilai terbesar ke nilai terkecil)

In [67]:
wine_simple_df.sort_values(by='price', ascending=False).head()

      country                                              title   price
1558   France                      Château Margaux 2009  Margaux  1900.0
1575   France           Château Mouton Rothschild 2009  Pauillac  1300.0
1571   France            Château Haut-Brion 2009  Pessac-Léognan  1200.0
1566   France  Château La Mission Haut-Brion 2009  Pessac-Léo...  1100.0
347   Germany  Robert Weil 2014 Kiedrich Gräfenberg Trockenbe...   775.0

In [68]:
wine_simple_df.sort_values(by=['country', 'title']).head()

        country                                       title  price
5902  Argentina                  2 Copas 2009 Red (Mendoza)    8.0
7076  Argentina        Achaval-Ferrer 2007 Malbec (Mendoza)   29.0
6287  Argentina  Acordeón 2012 Cabernet Sauvignon (Mendoza)    9.0
183   Argentina               Alamos 2007 Torrontés (Salta)   12.0
1851  Argentina                   Alamos 2013 Red (Mendoza)   13.0

#### Kasus: menampilkan daftar harga terrendah dan tertinggi untuk setiap variety wine, data diurutkan secara descending berdasarkan harga terrendah dan diikuti harga tertinggi.

In [69]:
wine_df.groupby('variety')['price'].agg(['min', 'max']).sort_values(by=['min','max'], ascending=False).head()

              min    max
variety
Muscadelle  350.0  350.0
Tokaji      175.0  175.0
Aleatico     55.0   55.0
Moscadello   55.0   55.0
Cerceal      50.0   50.0

#### Kasus: menampilkan rata-rata points yang diberikan oleh tiap reviewer (```taster_name```)

In [70]:
wine_df.groupby('taster_name')['points'].mean().head()

taster_name
Alexander Peartree    85.825000
Anna Lee C. Iijima    88.267857
Anne Krebiehl MW      90.186275
Carrie Dykes          86.333333
Fiona Adams           86.333333
Name: points, dtype: float64

#### Kasus: menampilkan jumlah wine (```title```) yang dihasilkan di tiap negara (```country```) untuk tiap jenis wine (```variety```)

In [71]:
wine_df.groupby(['country', 'variety'])['title'].count().sort_values(ascending=False).head(10)

country   variety
US        Pinot Noir                  708
          Cabernet Sauvignon          551
          Chardonnay                  494
France    Bordeaux-style Red Blend    346
Italy     Red Blend                   266
US        Syrah                       245
          Red Blend                   212
Italy     Nebbiolo                    204
Portugal  Portuguese Red              190
France    Chardonnay                  189
Name: title, dtype: int64

## Mengubah nama kolom pada DataFrame
Perubahan nama kolom pada DataFrame dapat dilakukan dengan memanfaatkan method ```rename```

In [72]:
wine_df.rename(columns={'points': 'score'}).head()

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards,star
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,9391,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,9390,None
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,9389,None
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,9388,None
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,9387,None

#### Mengubah label/nama index dengan method ```rename_axis```

In [73]:
wine_df.rename_axis('baris', axis='rows').head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards,star
baris,,,,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,9391,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,9390,None
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,9389,None
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,9388,None
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,9387,None

In [74]:
wine_df.rename_axis('baris', axis='rows').rename_axis('kolom', axis='columns').head()

kolom,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards,star
baris,,,,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,9391,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,9390,None
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,9389,None
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,9388,None
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,9387,None